hydra:
  job:
    chdir: True

downsample_class: # Class to downsample, e.g., "cat"
downsample_ratio: 0.01 # How many examples to keep
naive_oversample: false
naive_undersample: false
smote: false
adasyn: false
label_smoothing: false
class_weighting: false
name: basic_experiment
epochs: 100
batch_size: 128
learning_rate: 0.1
val_size: 0.2
num_workers: 2
seed: 42
augmentations:
    - name: ToTensor
    - name: Normalize
      params:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
    - name: RandomCrop
      params:
          size: 32
          padding: 4
    - name: RandomHorizontalFlip
      params:
          p: 0.5
    # - name: ColorJitter
    #   params:
    #       brightness: 0.5
    #       hue: 0.3
    # - name: RandomPerspective
    #   params:
    #       distortion_scale: 0.2
    #       p: 1.0
    #       fill: 0
    # - name: RandomRotation
    #   params:
    #       degrees: 180
    #       fill: 0
    # - name: RandomSolarize
    #   params:
    #       threshold: 0.75
    #       p: 0.5
test_augmentations:
    - name: ToTensor
    - name: Normalize
      params:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
