hydra:
  run:
    dir: .      # Use the current working directory for running the job.
  job:
    chdir: False  # Do not change the working directory.

dynamic_upsample: False
num_dynamic_upsample: 50

downsample_class: # Class to downsample, e.g., "cat"
downsample_ratio: 0.01 # How many examples to keep
naive_oversample: false
naive_undersample: false
keep_only_cat: false
smote: false
adasyn: false
label_smoothing: false
class_weighting: false
add_extra_images: True
extra_images_dir: /home/karol/sd-imbalance/flux_tests
max_extra_images: 4950
name: base
epochs: 100
compile: False
batch_size: 128
learning_rate: 0.1
val_size: 0.2
num_workers: 2
seed: 42
augmentations:
    # - name: FluxReduxAugment
    #   params:
    #     guidance_scale: 2.5
    #     num_inference_steps: 50
    #     seed: 0
    #     device: "cuda"
    #     probability: 0.3
    - name: ToTensor
    - name: Normalize
      params:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
    - name: RandomCrop
      params:
          size: 32
          padding: 4
    - name: RandomHorizontalFlip
      params:
          p: 0.5
    # Resize to 32x32
    - name: Resize
      params:
          size: 32
          interpolation: "nearest"
test_augmentations:
    - name: ToTensor
    - name: Normalize
      params:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
    - name: Resize
      params:
          size: 32
          interpolation: "nearest"

checkpoint_path: 
visualize_feature_maps: False  # Set to true to only visualize feature maps
visualize_trained_model: True

downsample_classes:
  "airplane": 1
  "automobile": 1
  "bird": 1
  "cat": 0.01
  "deer": 1
  "dog": 1
  "frog": 1
  "horse": 1
  "ship": 1
  "truck": 1


# Multi-class image addition
extra_images_per_class:
  "airplane": 0
  "automobile": 0
  "bird": 0
  "cat": 4950
  "deer": 0
  "dog": 0
  "frog": 0
  "horse": 0
  "ship": 0
  "truck": 0

normalize_synthetic: 'mean_std'  # None, 'mean_std', or 'clahe'
similarity_filter:   # None, 'original', or 'synthetic'
similarity_threshold: 0.85       # Threshold for similarity filtering
reference_sample_size: 50        # Number of reference images to use