hydra:
  run:
    dir: .      # Use the current working directory for running the job.
  job:
    chdir: False  # Do not change the working directory.

# Oversampling, Undersampling and regularization methods
naive_oversample: false
smote: false
adasyn: false
naive_undersample: false
label_smoothing: false
class_weighting: false

# Wandb
name: base # WANDB project name

# Project/model settings
epochs: 100
compile: True
batch_size: 256
learning_rate: 0.1
val_size: 0.2
num_workers: 2
seed: 42
checkpoint_path: 
visualize_trained_model: True
freeze_backbone: False
fine_tune_on_real_data: False

# Dataset settings
augmentations:
    - name: ToTensor
    - name: RandomCrop
      params:
          size: 32
          padding: 4
    - name: RandomHorizontalFlip
      params:
          p: 0.5
    - name: Resize
      params:
          size: 32
          interpolation: "nearest"
test_augmentations:
    - name: ToTensor
    - name: Resize
      params:
          size: 32
          interpolation: "nearest"
cutmix_or_mixup: False


# Extra images settings
add_extra_images: False
extra_images_dir: /home/karol/sd-imbalance/flux_modified
downsample_classes:
  "airplane": 1
  "automobile": 1
  "bird": 1
  "cat": 0.1
  "deer": 1
  "dog": 1
  "frog": 1
  "horse": 1
  "ship": 1
  "truck": 1
extra_images_per_class:
  "airplane": 0
  "automobile": 0
  "bird": 0
  "cat": 4500
  "deer": 0
  "dog": 0
  "frog": 0
  "horse": 0
  "ship": 0
  "truck": 0
normalize_synthetic: 'mean_std'  # None, 'mean_std', or 'clahe'
similarity_filter:   # None, 'original', or 'synthetic'
similarity_threshold: 0.8      # Threshold for similarity filtering
reference_sample_size: 50        # Number of reference images to use

# Dynamic upsampling via active learning
dynamic_upsample: False
num_dynamic_upsample: 50
