dataset:
  name: cifar10          # or imagenet
  path: ./data           # Path to dataset
  num_classes: 10        # Number of classes for CIFAR-10

  undersample:
    # CIFAR-10 classes dict: {0: 'airplane', 1: 'automobile', 2: 'bird', 3: 'cat', 4: 'deer', 5: 'dog', 
    # 6: 'frog', 7: 'horse', 8: 'ship', 9: 'truck'}
    classes: [3]   # Classes to undersample
    percentage: 10      # Percentage of original data to retain for these classes

  augmentation:          # Optional: Data augmentation settings
    apply: true
    type: random_flip
