# scripts/generate_cifar.py

import os
import random
from PIL import Image
import torch
from diffusers import StableDiffusionXLPipeline
from tqdm import tqdm
import gc
from typing import (
    List,
    Dict,
    Optional,
)

"""
This script generates synthetic images for all 10 CIFAR-10 classes
using the Stable Diffusion XL Turbo pipeline. It uses an extensive
prompting strategy with class-specific descriptors, contexts, and
general quality modifiers to create diverse and realistic images.
Images are saved into class-specific subfolders, and filenames are compatible
with data.py's image parsing.
"""
cifar10_classes: List[str] = [
    "airplane",
    "automobile",
    "bird",
    "cat",
    "deer",
    "dog",
    "frog",
    "horse",
    "ship",
    "truck",
]

class_specific_concepts: Dict[str, Dict[str, List[str]]] = {
    "airplane": {
        "descriptor_type": [
            "jet airplane",
            "propeller plane",
            "biplane",
            "passenger airplane",
            "cargo plane",
            "military aircraft",
            "small airplane",
            "large airplane",
            "vintage airplane",
            "modern airplane",
            "commercial airliner",
            "private jet",
            "fighter jet",
            "bomber plane",
            "stealth aircraft",
            "seaplane",
            "floatplane",
            "amphibious aircraft",
            "stunt plane",
            "aerobatic plane",
            "crop duster",
            "agricultural plane",
            "glider",
            "sailplane",
            "supersonic jet",
            "jumbo jet",
            "regional jet",
            "turboprop plane",
            "twin-engine airplane",
            "single-engine airplane",
            "high-wing airplane",
            "low-wing airplane",
            "delta wing airplane",
            "swept-wing airplane",
            "canard wing airplane",
            "red airplane",
            "blue airplane",
            "white airplane",
            "silver airplane",
            "camouflaged airplane",
            "metallic airplane",
            "shiny airplane",
            "rusty airplane",
            "old airplane",
            "new airplane",
            "experimental aircraft",
            "prototype airplane",
            "reconnaissance plane",
            "surveillance aircraft",
            "drone (large UAV style)",
            "airliner at gate",
            "parked jet",
            "taxiing airplane",
            "grounded plane",
            "charter plane",
            "executive jet",
            "historical aircraft",
            "WWII airplane",
            "jetliner",
            "commuter plane",
            "training aircraft",
            "light aircraft",
            "ultralight airplane",
            "business jet",
            "intercontinental jet",
            "long-range airplane",
            "short-haul airplane",
            "wide-body airplane",
            "narrow-body airplane",
            "jet fighter in flight",
            "propeller plane on grass",
            "biplane from the 1920s",
            "passenger plane window view",
            "massive cargo plane",
            "fighter jet squadron",
            "tiny propeller plane",
            "enormous passenger jet",
            "antique airplane",
            "futuristic concept airplane",
            "airbus airplane",
            "boeing airplane",
            "cessna airplane",
            "piper airplane",
            "spitfire airplane",
            "mustang airplane",
            "blackbird SR-71 style",
            "concorde style airplane",
            "flying wing design",
            "tiltrotor aircraft",
            "airship (dirigible style)",
            "hot air balloon (aircraft)",
            "jet engine detail",
            "propeller detail",
            "airplane wing",
            "airplane tail fin",
            "cockpit view (external)",
            "landing gear detail",
            "airplane silhouette",
            "damaged airplane",
            "airplane model toy",
        ],
        "context_action": [
            "flying in the clear blue sky",
            "on the runway preparing for takeoff",
            "taking off from airport",
            "landing smoothly",
            "parked at the airport gate",
            "flying high above the clouds",
            "during a vibrant sunset flight",
            "in clear daylight sky",
            "performing complex aerobatics",
            "flying in tight formation",
            "taxiing on the tarmac",
            "inside a large hangar",
            "undergoing maintenance",
            "refueling on the ground",
            "banking sharply in the air",
            "climbing steeply after takeoff",
            "descending for landing",
            "flying over a city skyline",
            "flying over mountains",
            "flying over the ocean",
            "flying through light clouds",
            "in foggy weather conditions",
            "during light rain",
            "in a snowstorm (airborne)",
            "leaving long contrails",
            "approaching the destination airport",
            "parked near a terminal building",
            "waiting for clearance",
            "on a grassy airfield",
            "on a remote airstrip",
            "reflecting in water (seaplane)",
            "stored in a museum",
            "as part of an airshow",
            "at night on illuminated runway",
            "during sunrise",
            "over a desert landscape",
            "over a forest canopy",
            "near a rainbow",
            "circling the airport",
            "on final approach",
            "parked among other airplanes",
            "being loaded with cargo",
            "passengers boarding",
            "military jet scrambling",
            "glider being towed",
            "seaplane taking off from water",
            "floatplane docked at a lake",
            "crop duster spraying fields",
            "vintage plane in black and white photo style",
            "modern jet at international airport",
            "flying low over terrain",
            "experiencing turbulence (visual cues)",
            "on autopilot (conceptual)",
            "night flight with cabin lights visible",
            "emergency landing scenario",
            "airplane shadow on the ground",
            "view from control tower",
            "flying past a landmark",
            "in a steep dive",
            "pulling up from a dive",
            "crossing international airspace",
            "on a transatlantic flight path",
            "arctic expedition plane",
            "tropical island hopping plane",
            "mountain rescue plane",
            "parked on an aircraft carrier deck",
            "jet wash visible",
            "landing gear deploying",
            "flaps extending for landing",
            "engine glow at night",
            "airplane wreckage (post-crash)",
            "air traffic control radar screen style",
            "blueprint schematic of airplane",
            "wind tunnel testing",
            "flight simulator view (external)",
            "airplane reflected in sunglasses",
            "toy airplane in child's hand",
            "paper airplane mid-flight",
            "remote control airplane flying",
            "airplane nose art visible",
            "tail fin logo prominent",
            "low altitude flyby",
            "supersonic shockwave (visual)",
            "aerial refueling",
            "paratroopers jumping",
        ],
    },
    "automobile": {
        "descriptor_type": [
            "sedan car",
            "suv vehicle",
            "convertible with top down",
            "sports car",
            "vintage car",
            "modern car",
            "pickup truck",
            "electric car (EV)",
            "red car",
            "blue car",
            "family car",
            "hatchback",
            "coupe",
            "muscle car",
            "luxury sedan",
            "economy car",
            "minivan",
            "jeep style off-roader",
            "rally car",
            "taxi cab",
            "police car",
            "ambulance van",
            "delivery van",
            "limousine",
            "classic car from 1950s",
            "hot rod car",
            "dune buggy",
            "station wagon",
            "black car",
            "white car",
            "silver car",
            "yellow car",
            "green car",
            "orange car",
            "grey car",
            "damaged car",
            "rusty old car",
            "shiny new car",
            "concept car design",
            "hybrid vehicle",
            "compact car",
            "subcompact car",
            "full-size sedan",
            "crossover SUV",
            "armored car",
            "food truck",
            "ice cream truck",
            "camper van",
            "RV motorhome",
            "school bus",
            "racing car on track",
            "formula 1 style car",
            "NASCAR style car",
            "drag racing car",
            "go-kart",
            "three-wheeled car",
            "microcar",
            "exotic supercar",
            "hypercar",
            "tuner car",
            "lowrider car",
            "monster truck (parked)",
            "antique car (pre-1930s)",
            "customized car",
            "off-road truck",
            "4x4 vehicle",
            "electric pickup truck",
            "hydrogen fuel cell car",
            "autonomous vehicle prototype",
            "presidential limousine",
            "hears",
            "utility vehicle",
            "golf cart",
            "forklift truck",
            "armored personnel carrier (APC)",
            "vintage police car",
            "classic taxi",
            "woody wagon",
            "muscle car with stripes",
            "convertible with top up",
            "car with roof rack",
            "car covered in stickers",
            "car with spoiler",
            "car with large wheels",
            "car with tinted windows",
            "dirty muddy car",
            "clean polished car",
            "car with flat tire",
            "car missing a door",
            "crashed car",
            "restored classic car",
            "kit car",
            "muscle car burnout",
            "electric scooter (vehicle)",
            "electric bicycle (vehicle)",
            "futuristic flying car concept",
            "solar powered car concept",
            "streamlined car",
            "aerodynamic design car",
            "boxy car",
        ],
        "context_action": [
            "driving on a multi-lane highway",
            "parked on a busy city street",
            "cruising on a scenic coastal road",
            "inside a home garage",
            "refueling at a gas station",
            "stuck in heavy traffic",
            "driving through pouring rain",
            "illuminated by streetlights at night",
            "covered in fresh snow",
            "driving off-road on a dirt trail",
            "on a race track during a race",
            "going through an automatic car wash",
            "parallel parking maneuver",
            "towing a small trailer",
            "crossing a large bridge",
            "navigating a winding mountain road",
            "driving through a desert landscape",
            "on a quiet country lane",
            "parked in a suburban driveway",
            "under bright city neon lights",
            "reflecting city buildings",
            "abandoned in a field",
            "being repaired in a workshop",
            "displayed in a car showroom",
            "in a crowded shopping mall parking lot",
            "stuck deep in mud",
            "kicking up dust on a gravel road",
            "car show exhibition",
            "vintage car rally",
            "police car in pursuit",
            "taxi waiting for fare",
            "ambulance speeding with lights",
            "delivery van dropping off packages",
            "limousine arriving at event",
            "hot rod drag racing",
            "off-roader climbing rocks",
            "camper van parked at campsite",
            "school bus picking up children",
            "monster truck crushing smaller cars",
            "driving through tunnel",
            "parked overlooking a viewpoint",
            "electric car at charging station",
            "autonomous car navigating city",
            "car covered by car cover",
            "test driving a new car",
            "car interior view (from outside)",
            "engine compartment visible",
            "headlights turned on",
            "taillights glowing",
            "tire tracks in sand/snow",
            "reflection in a puddle",
            "driving past famous landmark",
            "car chase scene",
            "joyriding scenario",
            "learner driver practicing",
            "car being washed by hand",
            "getting a tire changed",
            "being towed by tow truck",
            "involved in minor fender bender",
            "driving through autumn leaves",
            "parked under cherry blossoms",
            "car ferry transport",
            "drive-in movie theater",
            "valet parking",
            "car boot sale / trunk sale",
            "driving alongside a train",
            "parked next to a beach",
            "car transporter truck loaded",
            "driving in fog",
            "hydroplaning on wet road",
            "skidding on ice",
            "drifting around a corner",
            "doing donuts in parking lot",
            "car stereo visible (external)",
            "GPS navigation screen visible (external)",
            "car keys dangling",
            "exhaust smoke visible",
            "car alarm sounding (visual cue)",
            "convertible driving in sunshine",
            "family road trip",
            "commuter traffic crawl",
            "luxury car dealership",
            "junkyard full of old cars",
            "car submerged in water",
            "car on fire",
        ],
    },
    "bird": {
        "descriptor_type": [
            "songbird",
            "bird of prey",
            "eagle",
            "sparrow",
            "robin",
            "blue jay",
            "parrot",
            "hummingbird",
            "owl",
            "colorful bird",
            "small bird",
            "large bird",
            "pigeon",
            "crow",
            "raven",
            "seagull",
            "duck",
            "goose",
            "swan",
            "flamingo",
            "penguin (on land/ice)",
            "toucan",
            "woodpecker",
            "cardinal",
            "finch",
            "hawk",
            "falcon",
            "vulture",
            "ostrich",
            "emu",
            "pelican",
            "stork",
            "heron",
            "kingfisher",
            "magpie",
            "chickadee",
            "exotic bird",
            "tropical bird",
            "water bird",
            "migratory bird",
            "flock of birds",
            "male bird (plumage)",
            "female bird (plumage)",
            "baby bird (chick)",
            "nestling",
            "fledgling bird",
            "wading bird",
            "shorebird",
            "game bird (pheasant)",
            "bird with long beak",
            "bird with crest",
            "bird with bright feathers",
            "camouflaged bird",
            "black bird",
            "white bird",
            "brown bird",
            "grey bird",
            "yellow bird",
            "green bird",
            "blue bird",
            "tiny hummingbird",
            "majestic eagle",
            "common pigeon",
            "intelligent crow",
            "elegant swan",
            "funny penguin",
            "vibrant parrot",
            "nocturnal owl",
            "swift falcon",
            "soaring hawk",
            "large ostrich",
            "graceful heron",
            "fishing kingfisher",
            "chattering magpie",
            "singing robin",
            "pecking woodpecker",
            "red cardinal",
            "cooing dove",
            "honking goose",
            "quacking duck",
            "perched bird",
            "flying bird",
            "bird in flight",
            "bird taking off",
            "bird landing",
            "bird silhouette",
            "bird feather detail",
            "bird eye close-up",
            "bird beak close-up",
            "bird feet/talons",
            "fluffy chick",
            "bird egg in nest",
            "albino bird",
            "melanistic bird",
            "bird with prey",
            "domesticated bird (canary)",
            "pet bird (parakeet)",
            "talking parrot",
            "bird illustration style",
            "origami bird",
        ],
        "context_action": [
            "perched on a leafy branch",
            "flying freely in blue sky",
            "in a nest with small eggs",
            "on the ground foraging for food",
            "drinking water from a puddle",
            "preening its colorful feathers",
            "eating seeds from a bird feeder",
            "deep within a dense forest",
            "near the edge of a calm lake",
            "silhouette against a setting sun",
            "taking a bath in a bird bath",
            "catching a worm or insect",
            "soaring high on thermal currents",
            "diving towards water for fish",
            "perched precariously on a fence post",
            "sitting on a city rooftop",
            "balanced on a telephone wire",
            "inside a decorative birdcage",
            "defending nest from predator",
            "busily building a nest with twigs",
            "feeding its hungry young chicks",
            "migrating in a large V formation",
            "wading gracefully in shallow water",
            "pecking at seeds scattered on ground",
            "singing loudly from a treetop",
            "hiding amongst dense foliage",
            "standing on a sandy beach shoreline",
            "in an urban park environment",
            "exploring a backyard garden",
            "against a backdrop of snowy landscape",
            "reflected in still water",
            "flying through morning mist",
            "during light rainfall",
            "in a wildlife sanctuary",
            "observed through binoculars",
            "hummingbird hovering near flower",
            "owl perched silently at night",
            "eagle scanning from high cliff",
            "seagulls following a fishing boat",
            "ducks swimming in a pond",
            "swan gliding elegantly on lake",
            "flamingo standing on one leg",
            "penguin colony on ice floe",
            "toucan showing its large beak",
            "woodpecker drumming on tree trunk",
            "parrots talking in rainforest canopy",
            "crows gathering on power lines",
            "pigeons flocking in city square",
            "sparrow chirping on windowsill",
            "robin pulling worm from lawn",
            "bird trapped indoors",
            "releasing a bird into the wild",
            "banding a wild bird (research)",
            "bird interacting with another species",
            "bird mobbing a predator (owl/hawk)",
            "dust bathing on the ground",
            "sunbathing with wings spread",
            "roosting together at night",
            "bird tracks in sand or snow",
            "bird dropping feather",
            "close-up of intricate nest structure",
            "empty nest after fledging",
            "bird of prey carrying prey",
            "bird flying into sunset",
            "bird flying out of frame",
            "bird caught in slow motion flight",
            "time-lapse of nest building",
            "bird looking directly at camera",
            "bird tilting its head curiously",
            "bird puffing up feathers (cold/aggression)",
            "bird stretching its wings",
            "bird landing on a human hand (tame)",
            "bird attacking its reflection",
            "bird weaving through trees",
            "bird flying over waterfall",
            "bird near a human dwelling",
            "bird in flight over open field",
            "bird drinking nectar",
            "bird eating fruit from tree",
            "bird eating fish",
            "bird swallowing prey whole",
            "bird camouflaged against bark",
            "bird camouflaged in grass",
            "bird in a zoo enclosure",
            "taxidermy bird display",
        ],
    },
    "cat": {
        "descriptor_type": [
            "tabby cat",
            "black cat",
            "white cat",
            "ginger cat",
            "siamese cat",
            "persian cat",
            "fluffy cat",
            "sleek short-haired cat",
            "kitten",
            "old cat",
            "domestic cat",
            "maine coon cat",
            "bengal cat",
            "sphynx cat (hairless)",
            "scottish fold cat",
            "calico cat",
            "tortoiseshell cat",
            "grey cat",
            "blue russian cat",
            "ragdoll cat",
            "striped cat",
            "spotted cat",
            "long-haired cat",
            "fat cat",
            "skinny cat",
            "playful cat",
            "sleepy cat",
            "curious cat",
            "grumpy cat",
            "alert cat",
            "hunting cat",
            "lazy cat",
            "affectionate cat",
            "scared cat",
            "angry cat (hissing)",
            "stray cat",
            "alley cat",
            "pampered house cat",
            "rescued cat",
            "wild cat (small, e.g., bobcat)",
            "tuxedo cat (black and white)",
            "orange tabby cat",
            "silver tabby cat",
            "brown tabby cat",
            "cream colored cat",
            "cat with green eyes",
            "cat with blue eyes",
            "cat with yellow eyes",
            "cat with odd eyes",
            "polydactyl cat (extra toes)",
            "cat with collar",
            "cat with bell",
            "cat with bow tie",
            "cat in costume",
            "cat with clipped ear (feral)",
            "wet cat",
            "muddy cat",
            "cat covered in dust",
            "well-groomed cat",
            "scruffy cat",
            "mother cat with kittens",
            "pair of cats interacting",
            "cat silhouette",
            "cat paw close-up",
            "cat whisker detail",
            "cat tail swishing",
            "cat ear twitching",
            "cat nose close-up",
            "cat yawning widely",
            "cat stretching",
            "cat kneading paws ('making biscuits')",
            "cartoon cat style",
            "illustrated cat",
            "ceramic cat figurine",
            "cat shaped object",
            "famous cartoon cat (e.g., Garfield style)",
            "cheshire cat style grin",
            "lucky cat (maneki-neko)",
            "catbus style (fantasy)",
            "battle cat style (fantasy)",
            "robotic cat",
            "cyborg cat",
            "skeleton cat (halloween)",
            "ghost cat",
            "zombie cat",
            "cat merged with another animal",
            "cat made of clouds",
            "cat made of fire",
            "cat made of stars",
            "cat constellation",
            "tiny kitten",
            "large maine coon",
            "hairless sphynx",
            "fluffy persian",
            "energetic bengal",
        ],
        "context_action": [
            "sitting comfortably on a plush sofa",
            "sleeping peacefully in a warm sunbeam",
            "actively playing with a toy mouse",
            "looking intently out a window",
            "skillfully climbing a tall tree",
            "drinking milk from a ceramic bowl",
            "captured mid-yawn",
            "curled up snugly inside a cardboard box",
            "walking stealthily along a wooden fence",
            "hiding playfully under a bed",
            "chasing a red laser pointer dot",
            "scratching vigorously on a sisal post",
            "curled up contentedly on a person's lap",
            "grooming its fur meticulously",
            "stalking an unseen prey in the grass",
            "begging for food near bowl",
            "jumping gracefully onto furniture",
            "hiding shyly behind a curtain",
            "exploring a lush green garden",
            "napping inconveniently on a laptop keyboard",
            "watching birds outside the window",
            "batting playfully at a dangling string",
            "sitting regally in a wicker laundry basket",
            "patrolling its territory outdoors",
            "meowing insistently at a closed door",
            "peeking around a corner",
            "sleeping in an unusual position",
            "interacting with another cat",
            "being petted by a human hand",
            "startled by a sudden noise",
            "licking its paw",
            "rubbing against a person's legs",
            "arched back, fur standing on end",
            "crouching low before pouncing",
            "carrying a toy in its mouth",
            "sleeping on a stack of books",
            "sitting on a windowsill",
            "in a pet carrier",
            "at the veterinarian's office",
            "wearing a cone of shame",
            "playing with water dripping from faucet",
            "trying to fit into a small space",
            "batting at christmas tree ornaments",
            "covered in cobwebs from exploring",
            "with catnip nearby",
            "mother cat nursing kittens",
            "kitten learning to walk",
            "old cat moving slowly",
            "cat walking on a leash (uncommon)",
            "cat riding in a car (in carrier)",
            "cat on a bookshelf",
            "cat near a fireplace",
            "cat in snowy environment",
            "cat walking on wet pavement",
            "cat silhouette against the moon",
            "cat eyes glowing in the dark",
            "close-up of cat's patterned fur",
            "cat leaving paw prints in dust",
            "cat jumping over obstacle",
            "cat falling (safely)",
            "cat interrupting video call",
            "cat stealing food",
            "cat opening a door/cabinet",
            "cat fascinated by reflection",
            "cat sleeping with a dog",
            "cat in a funny pose",
            "cat meme recreation",
            "cat wearing tiny hat",
            "cat giving 'judgmental' look",
            "cat 'loaf' position",
            "cat 'sploot' position",
            "cat hiding in paper bag",
            "cat batting at mobile phone screen",
            "cat enjoying being brushed",
            "cat ignoring its owner",
            "cat bringing 'gift' (toy/leaf)",
            "cat walking across piano keys",
            "cat drinking from toilet (undesirable)",
            "cat fascinated by vacuum cleaner",
            "cat sleeping on clean laundry",
            "cat portrait photograph",
            "cat painting (art style)",
            "cat sculpture",
            "cat tattoo design",
            "cat emoji representation",
        ],
    },
    "deer": {
        "descriptor_type": [
            "buck with large antlers",
            "doe (female deer)",
            "fawn (young deer)",
            "white-tailed deer",
            "mule deer",
            "majestic stag",
            "group of deer (herd)",
            "young deer",
            "alert deer",
            "reindeer (caribou)",
            "elk (wapiti)",
            "moose",
            "sika deer",
            "red deer",
            "fallow deer",
            "axis deer (chital)",
            "roe deer",
            "pudú (tiny deer)",
            "water deer (with tusks)",
            "musk deer",
            "solitary buck",
            "mother doe with fawn",
            "camouflaged deer",
            "large buck",
            "small doe",
            "spotted fawn",
            "grazing deer",
            "running deer",
            "leaping deer",
            "swimming deer",
            "curious deer",
            "shy deer",
            "powerful stag",
            "gentle doe",
            "playful fawn",
            "deer with velvet antlers",
            "deer with shedding antlers",
            "piebald deer (patches of white)",
            "albino deer",
            "melanistic deer (dark)",
            "urban deer",
            "suburban deer",
            "forest deer",
            "mountain deer",
            "plains deer",
            "winter coat deer",
            "summer coat deer",
            "healthy deer",
            "skinny deer",
            "old stag",
            "yearling deer",
            "deer silhouette",
            "deer skull with antlers",
            "antler detail",
            "deer hoof print",
            "close-up deer eye",
            "deer nose sniffing air",
            "deer tail flicking",
            "regal elk",
            "massive moose",
            "graceful white-tailed deer",
            "mule deer with large ears",
            "reindeer in snow",
            "fallow deer with palmate antlers",
            "red deer stag roaring",
            "cartoon deer style",
            "illustrated deer",
            "deer figurine",
            "cave painting of deer",
            "heraldic deer symbol",
            "Bambi style deer",
            "fantasy deer (glowing antlers)",
            "spirit animal deer",
            "wooden carved deer",
            "origami deer",
            "deer trophy mount",
            "deer crossing sign",
            "deer camouflage pattern",
            "prehistoric deer (e.g., Megaloceros)",
            "mythical deer (e.g., Kirin)",
            "robotic deer",
            "crystal deer",
            "ice sculpture deer",
            "topiary deer",
            "constellation (Cervus)",
            "close up buck antlers",
            "doe nursing fawn",
            "fawn hiding in grass",
            "alert ears twitching",
            "deer looking back",
            "deer frozen in headlights",
            "deer jumping fence",
            "deer rubbing antlers on tree",
            "deer bedding down",
            "herd moving together",
        ],
        "context_action": [
            "standing in a misty morning forest",
            "grazing peacefully in a sunlit meadow",
            "running swiftly across an open field",
            "drinking carefully from a clear stream",
            "peeking cautiously through dense bushes",
            "walking through fresh snow",
            "at sunrise with golden light",
            "perfectly camouflaged amongst autumn woods",
            "carefully crossing a quiet country road",
            "startled and ready to bolt",
            "leaping gracefully over a fallen log",
            "sleeping curled up under a large tree",
            "two bucks locking antlers in a fight",
            "silhouetted against a dramatic sunset",
            "deep within the shadows of a pine forest",
            "crossing a shallow river",
            "foraging for acorns or berries",
            "walking along a high mountain ridge",
            "at the edge of a dense forest",
            "wandering into a suburban backyard",
            "in a protected national park setting",
            "near a tranquil mountain lake",
            "warning others with a raised white tail",
            "listening intently with large ears swiveling",
            "in autumn foliage",
            "during winter blizzard",
            "in spring with new fawns",
            "summer grazing in high pasture",
            "interacting with other wildlife (squirrels, birds)",
            "startled by hiker",
            "moose wading in marshy area",
            "elk bugling during rutting season",
            "reindeer pulling a sleigh (fantasy/cultural)",
            "deer caught in car headlights",
            "fawn taking its first steps",
            "doe cleaning her fawn",
            "buck rubbing velvet off antlers",
            "leaving tracks in mud",
            "jumping over a wire fence",
            "browsing leaves from low branches",
            "resting in tall grass",
            "looking directly at the camera",
            "running away from danger",
            "part of a large migrating herd",
            "visiting a salt lick",
            "deer outlined by moonlight",
            "reflected in a pond",
            "in a field of wildflowers",
            "near old barn",
            "through binoculars view",
            "camera trap photograph style",
            "wildlife documentary footage style",
            "cave painting depiction",
            "on a snowy mountainside",
            "in a redwood forest",
            "deer hiding from hunter (implied)",
            "injured deer limping",
            "deer swimming across lake",
            "young bucks play fighting",
            "doe cautiously leading fawn",
            "deer jumping through clearing",
            "grazing near farm animals",
            "startled by car horn",
            "sniffing the air for scent",
            "licking dew drops from leaves",
            "marking territory with scent gland",
            "standing regally on hilltop",
            "fawn camouflaged on forest floor",
            "mother doe being protective",
            "deer running alongside fence line",
            "in a managed forest environment",
            "near a waterfall",
            "during a solar eclipse (dramatic light)",
            "under a starry night sky",
            "in ancient woodland",
            "through morning ground fog",
            "in a wildlife rehabilitation center",
            "taxidermy deer head mounted",
            "illustration in field guide",
            "prehistoric cave art of deer hunt",
        ],
    },
    "dog": {
        "descriptor_type": [
            "golden retriever",
            "german shepherd",
            "labrador retriever",
            "poodle (standard/miniature/toy)",
            "beagle",
            "bulldog (english/french)",
            "small dog",
            "large dog",
            "puppy",
            "loyal dog",
            "fluffy dog",
            "dachshund",
            "boxer",
            "shih tzu",
            "yorkshire terrier",
            "siberian husky",
            "corgi (pembroke/cardigan)",
            "dalmatian",
            "rottweiler",
            "great dane",
            "chihuahua",
            "schnauzer (giant/standard/miniature)",
            "border collie",
            "australian shepherd",
            "sheepdog (old english)",
            "terrier (jack russell, scottie, etc.)",
            "hound (bloodhound, greyhound, etc.)",
            "working dog",
            "guard dog",
            "guide dog for the blind",
            "police dog (K9)",
            "rescue dog",
            "wet dog after swimming",
            "muddy dog after playing",
            "happy dog with tongue out",
            "sad dog with droopy ears",
            "angry dog snarling",
            "scared dog trembling",
            "old dog with grey muzzle",
            "energetic puppy",
            "mixed breed dog (mutt)",
            "mongrel",
            "designer dog breed (e.g., labradoodle)",
            "show dog",
            "pet dog",
            "hunting dog",
            "sled dog team",
            "lap dog",
            "shaggy dog",
            "short-haired dog",
            "long-haired dog",
            "wire-haired dog",
            "curly-haired dog (poodle)",
            "spotted dog (dalmatian)",
            "brindle coated dog",
            "black dog",
            "white dog",
            "brown dog",
            "golden dog",
            "grey dog",
            "tri-color dog",
            "merle patterned dog",
            "dog with floppy ears",
            "dog with pointy ears",
            "dog with long tail",
            "dog with docked tail",
            "dog with curly tail",
            "dog wearing collar",
            "dog wearing bandana",
            "dog wearing sweater",
            "dog in costume",
            "three-legged dog",
            "dog with cone of shame",
            "dog with expressive eyes",
            "dog silhouette",
            "dog paw print",
            "dog nose close-up",
            "dog wagging tail blur",
            "cartoon dog style",
            "illustrated dog",
            "dog statue",
            "famous movie dog (e.g., Lassie style)",
            "underdog hero type",
            "robotic dog",
            "cyborg dog",
            "ghost dog",
            "zombie dog",
            "werewolf (dog form)",
            "dog constellation (Canis Major/Minor)",
            "dog shaped cloud",
        ],
        "context_action": [
            "playing fetch enthusiastically in a park",
            "running joyfully on a sandy beach",
            "sitting calmly by a warm fireplace",
            "panting heavily after a long walk",
            "sleeping soundly on a soft rug",
            "waiting patiently by the front door",
            "riding with head out car window",
            "getting a soapy bath in a tub",
            "wagging its tail excitedly",
            "walking obediently on a leash",
            "chewing contentedly on a bone",
            "digging a hole energetically in the yard",
            "barking loudly at the mailman",
            "chasing its own tail in circles",
            "learning a new trick for a treat",
            "running through an agility course",
            "cuddling affectionately with its owner",
            "looking longingly out the window",
            "eating eagerly from its food bowl",
            "drinking water messily from a bowl",
            "hiking on a scenic mountain trail",
            "walking through a busy city park",
            "sniffing the ground intently",
            "meeting another dog politely",
            "guarding the house alertly",
            "sleeping inside a cozy dog house/kennel",
            "rolling playfully in green grass",
            "swimming in a lake or pool",
            "shaking off water vigorously",
            "covered in mud after outdoor fun",
            "begging for food at the dinner table",
            "bringing slippers or newspaper",
            "howling at the moon (or siren)",
            "tilting head curiously",
            "giving paw (shake hands)",
            "lying upside down with paws in air",
            "snuggling under blankets",
            "riding in a bicycle basket",
            "visiting the veterinarian",
            "recovering from surgery (with cone)",
            "guide dog leading a person",
            "police dog sniffing for clues",
            "rescue dog searching rubble",
            "sled dogs pulling a sled",
            "sheepdog herding sheep",
            "hunting dog pointing at game",
            "greyhound racing on track",
            "show dog posing in ring",
            "puppy tripping over own feet",
            "old dog sleeping most of the day",
            "dog interacting with cat",
            "dog playing with children",
            "dog scared of vacuum cleaner",
            "dog barking at squirrel",
            "dog burying a bone",
            "dog catching frisbee mid-air",
            "dog performing service task",
            "dog licking owner's face",
            "dog dreaming (twitching/whimpering)",
            "dog protecting its toy",
            "dog sitting patiently for portrait",
            "dog running alongside bicycle",
            "dog in obedience training class",
            "dog jumping up to greet someone",
            "dog relaxing in sunbeam",
            "dog leaving paw prints on floor",
            "dog tear stain marks visible",
            "dog drooling in anticipation",
            "dog smiling (anthropomorphic)",
            "dog giving 'puppy eyes'",
            "dog looking guilty after mischief",
            "dog investigating strange object",
            "dog barking in play",
            "dog growling defensively",
            "dog whimpering sadly",
            "dog exploring new environment",
            "dog riding on skateboard (trained)",
            "dog surfing (trained)",
            "dog wearing life jacket",
            "dog in animal shelter cage",
        ],
    },
    "frog": {
        "descriptor_type": [
            "green frog",
            "tree frog",
            "bullfrog",
            "poison dart frog",
            "camouflaged frog",
            "small frog",
            "large frog",
            "spotted frog",
            "striped frog",
            "brown frog",
            "grey frog",
            "yellow frog",
            "red-eyed tree frog",
            "leopard frog",
            "wood frog",
            "spring peeper frog",
            "goliath frog (huge)",
            "glass frog (translucent belly)",
            "horned frog (pacman frog)",
            "african clawed frog (aquatic)",
            "oriental fire-bellied toad",
            "common toad",
            "smooth skinned frog",
            "warty skinned toad",
            "brightly colored frog",
            "dull colored frog",
            "aquatic frog",
            "terrestrial frog",
            "burrowing frog",
            "arboreal frog (tree dwelling)",
            "tadpole (larva stage)",
            "froglet (metamorphosis stage)",
            "male frog calling",
            "female frog (gravid)",
            "pair of frogs mating (amplexus)",
            "frog skeleton",
            "frog fossil",
            "cartoon frog style",
            "illustrated frog",
            "frog prince fairytale style",
            "Kermit the Frog style",
            "Pepe the Frog style (meme)",
            "frog figurine",
            "origami frog",
            "frog dissection (educational)",
            "robotic frog",
            "crystal frog",
            "stone frog statue",
            "frog shaped candy",
            "frog life cycle diagram",
            "frog with long legs",
            "frog with short legs",
            "frog with sticky toe pads",
            "frog with webbed feet",
            "frog with bulging eyes",
            "frog tongue extended",
            "frog skin texture close-up",
            "frog eggs (frogspawn)",
            "tadpole with developing legs",
            "metamorphosing frog",
            "albino frog",
            "melanistic frog",
            "frog with unique pattern",
            "common european frog",
            "american bullfrog",
            "amazon milk frog",
            "white's tree frog (dumpy frog)",
            "tomato frog",
            "mossy frog (camouflaged)",
            "painted frog",
            "budgetts frog (wide-mouth)",
            "paradoxical frog (large tadpole, small frog)",
            "desert rain frog",
            "australian green tree frog",
            "bornean flat-headed frog (no lungs)",
            "gastric-brooding frog (extinct)",
            "psychadelic frog",
            "hairy frog (with skin filaments)",
            "flying frog (gliding)",
            "horned marsupial frog",
            "mimic poison frog",
            "blue poison dart frog",
            "golden poison frog",
            "strawberry poison dart frog",
            "green and black poison dart frog",
            "tiny thumbnail dart frog",
            "large chubby frog",
            "slender tree frog",
            "robust bullfrog",
            "camouflaged leaf litter frog",
        ],
        "context_action": [
            "sitting peacefully on a green lily pad",
            "hopping energetically through tall grass",
            "floating in a murky pond",
            "climbing skillfully up a wet plant stem",
            "catching an insect with its long tongue",
            "inflating its vocal sac while croaking",
            "partially submerged in still water",
            "resting on a mossy, wet rock",
            "deep within a lush rainforest environment",
            "calling loudly during the night",
            "hiding effectively under a large leaf",
            "swimming powerfully across a pond",
            "sunbathing quietly on a smooth log",
            "jumping suddenly into the water",
            "camouflaged perfectly against tree bark",
            "amongst reeds and cattails at water's edge",
            "near a small, trickling waterfall",
            "inside a humid glass terrarium",
            "crossing a damp forest path",
            "laying a mass of eggs (frogspawn) in water",
            "floating motionless on the water surface",
            "peeking its head out from the water",
            "eating a fly or small bug",
            "shedding its skin (and eating it)",
            "hibernating buried in mud (winter)",
            "aestivating in dry conditions (summer)",
            "tadpoles swimming in shallow water",
            "froglet climbing out of water",
            "tree frog sticking to window pane",
            "poison dart frog on rainforest floor",
            "bullfrog sitting by edge of lake",
            "toad burrowing into loose soil",
            "glass frog showing internal organs",
            "frog jumping away from predator",
            "frog being held gently in hands",
            "frog dissection in science lab",
            "frog legs prepared as food (cultural)",
            "frog depicted in ancient hieroglyphs",
            "frog used in scientific research",
            "frog habitat conservation area",
            "frog leaping between branches",
            "frog clinging to underside of leaf",
            "frog inflating body defensively",
            "frog playing dead (thanatosis)",
            "frog absorbing water through skin",
            "frog eye blinking slowly",
            "frog throat pulsating rhythmically",
            "frog leaving wet prints on surface",
            "close-up of sticky toe pads",
            "close-up of webbed feet",
            "frog surviving in urban pond",
            "frog chorus soundscape (visual)",
            "predator (snake/bird) stalking frog",
            "frog escaping predator",
            "frog interacting with another frog",
            "frog ignoring passing insect",
            "frog surveying surroundings",
            "frog in shallow puddle after rain",
            "frog climbing out of a well",
            "frog found in swimming pool",
            "frog sitting on garden gnome",
            "frog near pitcher plant",
            "frog under mushroom cap",
            "frog in slow motion jump",
            "time-lapse of tadpole development",
            "frog reflected in water droplet",
            "frog outlined by morning dew",
            "frog in terrarium with mist",
            "frog on brightly colored flower",
            "frog prince transformation concept",
            "frog catching mosquito",
            "frog eating smaller frog",
            "frog swallowing prey",
            "frog showing defensive colors",
            "frog camouflaged on mossy rock",
            "frog looking directly at viewer",
            "tiny frog on fingertip",
            "large bullfrog in hand",
            "frog jumping towards camera",
            "frog croaking sound visualised",
        ],
    },
    "horse": {
        "descriptor_type": [
            "brown horse",
            "white horse",
            "black horse",
            "stallion (male)",
            "mare (female)",
            "foal (young)",
            "wild horse (mustang)",
            "racehorse (thoroughbred)",
            "draft horse (clydesdale/shire)",
            "pony (shetland/welsh)",
            "majestic horse",
            "appaloosa (spotted)",
            "palomino (golden coat)",
            "pinto/paint (patches)",
            "bay horse (brown body, black points)",
            "chestnut horse (reddish-brown)",
            "grey horse (dappled/white)",
            "roan horse (mixed colors)",
            "buckskin horse",
            "dun horse (primitive markings)",
            "arabian horse",
            "quarter horse",
            "andalusian horse",
            "friesian horse (black, feathered feet)",
            "haflinger horse (chestnut, blonde mane)",
            "fjord horse (dun, distinct mane)",
            "gypsy vanner horse (pinto, feathered)",
            "miniature horse",
            "strong draft horse",
            "elegant riding horse",
            "fluffy pony",
            "sleek racehorse",
            "shaggy wild horse",
            "old horse",
            "young colt/filly",
            "horse with braided mane",
            "horse with flowing mane",
            "horse with shiny coat",
            "muddy horse",
            "wet horse",
            "horse wearing saddle",
            "horse wearing bridle",
            "horse wearing blanket",
            "horse with racing silks",
            "horse with decorative tack",
            "police horse",
            "cavalry horse (historical)",
            "jousting horse",
            "carriage horse",
            "plow horse",
            "therapy horse",
            "show jumping horse",
            "dressage horse",
            "endurance horse",
            "barrel racing horse",
            "horse silhouette",
            "horse skull",
            "horse hoof print",
            "close-up horse eye",
            "horse muzzle nuzzling",
            "horse tail swishing",
            "horse ear forward (alert)",
            "horse teeth (showing age)",
            "rearing horse",
            "bucking horse",
            "galloping horse",
            "trotting horse",
            "cantering horse",
            "walking horse",
            "grazing horse",
            "horse rolling on ground",
            "horse drinking water",
            "horse eating hay",
            "mother mare with foal",
            "herd of horses",
            "famous horse (e.g., Secretariat style)",
            "mythical horse (unicorn/pegasus)",
            "centaur (half horse)",
            "headless horseman's horse",
            "trojan horse (wooden)",
            "carousel horse",
            "rocking horse",
            "horse statue",
            "horse painting",
            "cave painting of horse",
            "robotic horse",
            "crystal horse",
            "ice sculpture horse",
            "topiary horse",
            "constellation (Equuleus)",
        ],
        "context_action": [
            "running free and wild in a large open field",
            "grazing peacefully in a green pasture",
            "standing calmly inside a wooden stable",
            "being ridden by a rider on a trail",
            "pulling a heavy wooden cart",
            "drinking cool water from a flowing river",
            "galloping swiftly around a dirt race track",
            "jumping skillfully over a high fence",
            "standing majestically in the mountains",
            "silhouetted against a beautiful sunset",
            "pulling a farmer's plow through a field",
            "herd of horses galloping together",
            "rolling playfully on its back in the grass",
            "being groomed carefully by a person",
            "wearing a saddle and bridle, ready to ride",
            "inside a horse trailer during transport",
            "playing in a muddy field",
            "standing in a snowy pasture in winter",
            "galloping along a sandy beach shoreline",
            "participating in a medieval jousting event",
            "police horse patrolling city streets",
            "part of a ceremonial parade",
            "looking curiously over a wooden fence",
            "nuzzling its owner affectionately",
            "foal nursing from its mother mare",
            "stallions fighting for dominance",
            "mare protecting her young foal",
            "horse wading through shallow water",
            "horse swimming across a lake",
            "horse lying down to rest or sleep",
            "horse eating hay from a feeder",
            "horse eating oats from a bucket",
            "horse licking a salt block",
            "horse being shoed by a farrier",
            "horse receiving veterinary care",
            "dressage horse performing elegant movements",
            "show jumper clearing an obstacle",
            "racehorse crossing the finish line",
            "wild mustangs running on plains",
            "pony being ridden by a child",
            "draft horse pulling a beer wagon",
            "carriage horse waiting for passengers",
            "horse tied to a hitching post",
            "horse spooked by sudden noise",
            "horse relaxing in sun",
            "horse interacting with other farm animals",
            "horse escaping from enclosure",
            "horse looking out from stable window",
            "horse reflected in water",
            "horse shadow long in evening light",
            "close-up of horse's powerful leg muscles",
            "close-up of flowing mane and tail",
            "horse wearing winter blanket",
            "horse sweating after exercise",
            "horse decorated for festival",
            "therapeutic riding session",
            "horse race photo finish",
            "endurance race through desert",
            "barrel racing pattern",
            "polo match in action",
            "horse farm landscape",
            "western rodeo scene",
            "historical cavalry charge",
            "horse in movie set",
            "horse painting in gallery",
            "rocking horse in nursery",
            "carousel horse on merry-go-round",
            "horse statue in city park",
            "unicorn in enchanted forest",
            "pegasus flying among clouds",
            "centaur hunting with bow",
            "horse pulling chariot",
            "horse in field of wildflowers",
            "horse under starry night sky",
            "horse nuzzling foal gently",
            "horse rearing up on hind legs",
            "horse bucking rider off",
            "horse playfully nipping another horse",
            "horse dozing while standing",
            "horse alert to distant sound",
        ],
    },
    "ship": {
        "descriptor_type": [
            "sailboat under sail",
            "large cruise ship",
            "massive container ship",
            "naval battleship",
            "small fishing boat",
            "luxury yacht",
            "old wooden sailing ship",
            "modern military ship",
            "commuter ferry boat",
            "powerful tugboat",
            "large ship",
            "small boat",
            "aircraft carrier",
            "submarine (surfaced)",
            "oil tanker ship",
            "bulk carrier ship",
            "oceanographic research vessel",
            "icebreaker ship",
            "catamaran",
            "trimaran",
            "dinghy",
            "canoe",
            "kayak",
            "gondola (venetian)",
            "paddle steamer boat",
            "destroyer warship",
            "frigate warship",
            "corvette warship",
            "nuclear submarine",
            "attack submarine",
            "pirate ship (historical)",
            "viking longship",
            "ancient greek galley",
            "chinese junk ship",
            "speedboat",
            "hovercraft",
            "lifeboat",
            "inflatable raft",
            "houseboat",
            "pontoon boat",
            "barge (river)",
            "dredging ship",
            "cable laying ship",
            "fireboat",
            "pilot boat",
            "coast guard cutter",
            "hospital ship",
            "car carrier ship (Ro-Ro)",
            "LNG carrier ship",
            "tall ship (multi-mast)",
            "schooner",
            "ketch",
            "yawl",
            "sloop",
            "brigantine",
            "ghost ship (e.g., Flying Dutchman)",
            "shipwreck (above/below water)",
            "ship in a bottle",
            "model ship",
            "origami boat",
            "paper boat",
            "toy boat",
            "ship blueprint/schematic",
            "ship propeller detail",
            "ship anchor detail",
            "ship funnel smoke",
            "ship mast and rigging",
            "ship bow wave",
            "ship wake",
            "ship radar dome",
            "rusty old ship",
            "shiny new yacht",
            "colorful fishing boat",
            "grey naval ship",
            "white cruise ship",
            "wooden tall ship",
            "sleek modern speedboat",
            "submersible vehicle",
            "floating dock",
            "dry dock with ship",
            "roman trireme",
            "egyptian reed boat",
            "polynesian voyaging canoe",
            "stealth ship design",
            "futuristic concept ship",
            "space battleship (sci-fi)",
            "flying ship (fantasy)",
            "steam powered ship",
            "diesel powered ship",
            "nuclear powered ship",
            "wind powered sailboat",
            "human powered canoe/kayak",
            "solar powered boat concept",
            "autonomous cargo ship",
            "cruise liner balcony view (external)",
        ],
        "context_action": [
            "sailing gracefully on the wide open ocean",
            "docked securely in a busy industrial harbor",
            "navigating carefully down a wide river",
            "battling through enormous waves in stormy seas",
            "anchored peacefully near a tropical island",
            "illuminated by a golden sunset over water",
            "passing slowly underneath a large bridge",
            "heavily loaded with colorful shipping containers",
            "reflecting perfectly in calm blue water",
            "emerging mysteriously from thick fog",
            "passing by a tall lighthouse on coast",
            "navigating through a narrow canal lock",
            "under construction in a huge shipyard",
            "resting in a dry dock for repairs",
            "leaving port heading for the sea",
            "arriving in port after long voyage",
            "participating in a sailing race (regatta)",
            "half-submerged shipwreck on a reef",
            "navigating carefully through icy waters (icebreaker)",
            "deep sea fishing boat hauling nets",
            "hosting whale watching tour",
            "river cruise boat passing scenery",
            "ferry transporting cars and passengers",
            "tugboat pulling a much larger vessel",
            "naval fleet maneuvering in formation",
            "sailing under the moonlight",
            "submarine surfacing dramatically",
            "aircraft carrier launching jets",
            "container ship being loaded/unloaded by cranes",
            "luxury yacht moored in Monaco harbor",
            "fishing boats returning with catch",
            "old sailing ship exploring new lands",
            "viking longship raiding coastline",
            "gondola navigating venetian canals",
            "paddle steamer on Mississippi river",
            "research vessel deploying equipment",
            "coast guard ship on patrol",
            "fireboat spraying water",
            "lifeboat drill scenario",
            "houseboat moored on calm river",
            "barge carrying coal or gravel",
            "ship caught in whirlpool (dramatic)",
            "ship running aground on sandbar",
            "ship navigating treacherous strait",
            "ship communicating with signal flags",
            "ship's horn blowing (visual cue)",
            "showing navigation lights at night",
            "cruise ship deck party visible",
            "ship trail visible from satellite view",
            "ship passing another ship closely",
            "small boat dwarfed by large wave",
            "kayaker paddling through rapids",
            "canoe trip in wilderness lake",
            "sailboat tacking against the wind",
            "catamaran speeding across water",
            "ship being cleaned (barnacles)",
            "ship repainting in dry dock",
            "ship launch ceremony",
            "maiden voyage celebration",
            "ship christening with champagne",
            "historical sea battle scene",
            "pirate ship attacking merchant vessel",
            "ghost ship appearing in mist",
            "ship in a bottle on shelf",
            "model ship sailing in pond",
            "paper boat floating down stream",
            "toy boat in bathtub",
            "ship engine room view (external)",
            "ship bridge view (external)",
            "ship sonar screen concept",
            "ship anchor dropping into water",
            "ship propeller turning underwater",
            "ship bow cutting through waves",
            "ship listing heavily to one side",
            "ship abandoned and adrift",
            "ship decorated for holiday",
            "military ship showing flags",
            "container ship in suez/panama canal",
            "ship navigating around storm",
            "ship finding safe harbor",
        ],
    },
    "truck": {
        "descriptor_type": [
            "pickup truck",
            "semi-truck (tractor-trailer)",
            "dump truck",
            "delivery truck/van",
            "fire truck",
            "monster truck",
            "old rusty truck",
            "modern pickup truck",
            "red truck",
            "blue truck",
            "heavy-duty truck",
            "tow truck (wrecker)",
            "garbage truck",
            "cement mixer truck",
            "tanker truck (fuel/milk)",
            "flatbed truck",
            "logging truck",
            "refrigerated truck (reefer)",
            "box truck",
            "utility truck (cherry picker)",
            "tow truck hauling a car",
            "military truck (cargo/troop)",
            "armored truck (bank truck)",
            "food truck (serving food)",
            "vintage pickup truck (1950s)",
            "lifted truck (large tires)",
            "small pickup truck",
            "large semi-truck cab",
            "eighteen-wheeler truck",
            "articulated lorry",
            "clean shiny truck",
            "dirty muddy truck",
            "overloaded truck",
            "long haul truck",
            "short haul truck",
            "dually truck (dual rear wheels)",
            "cab-over engine truck",
            "conventional cab truck",
            "sleeper cab semi-truck",
            "day cab semi-truck",
            "stake bed truck",
            "grain truck",
            "livestock truck",
            "car carrier truck",
            "mobile crane truck",
            "snow plow truck",
            "street sweeper truck",
            "vacuum truck (septic)",
            "water truck",
            "airport service truck",
            "bucket truck",
            "moving truck (U-Haul style)",
            "beverage delivery truck",
            "mail truck",
            "bookmobile truck",
            "SWAT team truck",
            "news satellite truck",
            "concrete pumper truck",
            "hazardous materials truck",
            "horse trailer truck",
            "truck with custom paint job",
            "truck with company logo",
            "truck with chrome details",
            "truck with large exhaust stacks",
            "truck with bull bar",
            "truck silhouette",
            "truck tire tread pattern",
            "truck engine detail (visible)",
            "truck grille close-up",
            "truck trailer hitch",
            "toy truck",
            "model truck",
            "lego truck",
            "cartoon truck style",
            "illustrated truck",
            "truck concept design",
            "electric semi-truck prototype",
            "hydrogen powered truck concept",
            "autonomous delivery truck",
            "futuristic truck",
            "cyberpunk style truck",
            "mad max style truck",
            "optimus prime style truck (transformer)",
            "wooden toy truck",
            "metal die-cast truck",
            "truck cab interior (from outside)",
            "truck trailer open (empty/full)",
            "truck driver stereotype (implied)",
            "truck stop sign",
            "truck weigh station sign",
        ],
        "context_action": [
            "driving on a wide multi-lane highway",
            "parked at a busy construction site",
            "loading or unloading goods at a warehouse",
            "navigating a bumpy dirt road",
            "parked at a large truck stop",
            "stuck deep in thick mud",
            "transporting large logs from forest",
            "hauling a long trailer behind cab",
            "maneuvering through dense city traffic",
            "driving at night with headlights blazing",
            "at a highway weigh station",
            "parked next to a loading dock",
            "delivering packages door-to-door",
            "responding to an emergency (fire truck)",
            "crushing cars at a monster truck rally",
            "collecting trash on residential street",
            "pouring cement at foundation site",
            "refueling at a diesel pump",
            "carrying heavy equipment on flatbed",
            "driving through mountain pass",
            "crossing a long suspension bridge",
            "driving on a snowy or icy road",
            "working on a farm",
            "pulling a boat trailer to lake",
            "on a long haul cross-country journey",
            "jackknifed semi-truck accident scene",
            "truck getting washed",
            "truck undergoing maintenance",
            "truck driver checking tires",
            "convoy of trucks on highway",
            "food truck serving customers",
            "armored truck making bank delivery",
            "military truck convoy moving troops",
            "utility truck repairing power lines",
            "tow truck pulling disabled vehicle",
            "garbage truck compacting trash",
            "cement mixer rotating drum",
            "tanker truck delivering fuel",
            "logging truck on forest road",
            "refrigerated truck at grocery store",
            "pickup truck tailgate party",
            "vintage truck at car show",
            "lifted truck climbing over obstacle",
            "moving truck parked outside house",
            "street sweeper cleaning road",
            "snow plow clearing highway",
            "dump truck tipping load of gravel",
            "livestock truck transporting animals",
            "car carrier loaded with new cars",
            "mobile crane lifting heavy object",
            "truck reflected in rain puddle",
            "truck kicking up dust cloud",
            "truck engine smoke (exhaust)",
            "truck air horn sounding (visual)",
            "truck back-up beeper sounding (visual)",
            "truck parked in scenic landscape",
            "truck driving through desert",
            "truck driving through forest",
            "truck beside railroad tracks",
            "truck near shipping port",
            "close-up of truck wheel/tire",
            "close-up of truck grille/logo",
            "view from inside truck cab (looking out)",
            "truck side mirror view",
            "truck trailer art/graphics",
            "autonomous truck driving test",
            "electric truck charging station",
            "hydrogen truck refueling concept",
            "truck simulator game view",
            "toy truck on playroom floor",
            "model truck collection display",
            "truck blueprint or design sketch",
            "optimus prime transforming",
            "mad max vehicle chase scene",
            "truck stop diner setting",
            "truck driver resting in sleeper cab",
            "truck covered in frost/ice",
            "truck decorated for parade",
            "truck pulling oversized load",
            "truck fleet parked in yard",
        ],
    },
}


# --- General Quality Modifiers ---
# Expanded list for more variety
quality_modifiers: List[str] = [
    "photorealistic",
    "high resolution",
    "detailed",
    "clear photo",
    "sharp focus",
    "cinematic lighting",
    "natural light",
    "realistic",
    "professional photography",
    "4k resolution",
    "8k resolution",
    "masterpiece",
    "best quality",
    "ultra detailed",
    "intricate details",
    "hdr (high dynamic range)",
    "studio quality photo",
    "dslr photo",
    "canon eos 5d mark iv",
    "nikon d850",
    "sony a7riii",
    "leica m11",
    "medium format photo",
    "film grain",
    "analog photo style",
    "vibrant colors",
    "muted colors",
    "monochrome",
    "black and white photo",
    "sepia toned",
    "shallow depth of field (bokeh)",
    "deep depth of field",
    "wide angle shot",
    "telephoto lens shot",
    "macro photography",
    "dramatic lighting",
    "soft lighting",
    "golden hour lighting",
    "blue hour lighting",
    "ambient light",
    "volumetric lighting",
    "ray tracing",
    "global illumination",
    "sharp image",
    "crisp details",
    "award-winning photography",
    "national geographic style photo",
    "associated press photo",
    "getty images style",
    "unsplash style photo",
    "cinematic composition",
    "rule of thirds composition",
    "dynamic angle",
    "low angle shot",
    "high angle shot",
    "aerial view",
    "birds-eye view",
    "over the shoulder shot",
    "point of view (pov)",
    "realistic rendering",
    "hyperrealistic",
    "surreal photography",
    "fine art photography",
    "documentary style photo",
    "candid shot",
    "posed shot",
    "environmental portrait",
    "focus stacking",
    "long exposure (motion blur)",
    "short exposure (freeze motion)",
    "crystal clear image",
    "perfect composition",
    "stunning visuals",
    "breathtaking photo",
    "epic scene",
    "atmospheric perspective",
    "lens flare effect",
    "god rays",
    "rim lighting",
    "backlighting",
    "front lighting",
    "diffused lighting",
    "hard shadows",
    "soft shadows",
    "realistic textures",
    "physically based rendering (PBR)",
    "octane render style",
    "unreal engine render style",
    "arnold render style",
    "v-ray render style",
    "high fidelity",
    "impeccable quality",
    "flawless image",
    "museum quality print",
    "portfolio worthy shot",
    "cinematic still",
    "movie screenshot style",
    "professionally color graded",
    "natural skin tones (if applicable)",
    "accurate colors",
    "sharp edges",
    "smooth gradients",
    "no artifacts",
    "clean background",
    "visually appealing",
]


def make_cifar10_style_images(
    base_folder: str = "./cifar10_synaug_sdxl_pdf_style_100k",
    num_images_per_class: int = 100000,
    classes: Optional[List[str]] = None,
    concept_map: Optional[Dict[str, Dict[str, List[str]]]] = None,
) -> None:
    """
    Generates images for specified CIFAR-10 classes using the Stable Diffusion XL Turbo pipeline.
    It constructs prompts using a rich set of class-specific descriptors, contexts, and
    general quality modifiers to create diverse and realistic images.
    Images are saved into class-specific subfolders, and filenames are structured to be compatible
    with `data.py`'s `_add_extra_images` method.

    Args:
        base_folder (str): The root directory where generated class folders will be created.
        num_images_per_class (int): The target number of images to generate for each class.
        classes (Optional[List[str]]): A list of class names (strings) for which to generate images.
                                       If None or empty, an error is printed.
        concept_map (Optional[Dict[str, Dict[str, List[str]]]]): A dictionary mapping class names to
                                                                   sub-dictionaries containing lists for
                                                                   'descriptor_type' and 'context_action'.
                                                                   If None or empty, an error is printed.
    """
    if classes is None or len(classes) == 0:
        print("Error: A list of classes must be provided.")
        return
    if concept_map is None or len(concept_map) == 0:
        print("Error: A class-to-concept dictionary must be provided.")
        return

    os.makedirs(base_folder, exist_ok=True)
    print(f"Base output directory: {base_folder}")

    print("Loading SDXL-Turbo pipeline...")
    pipe: Optional[StableDiffusionXLPipeline] = None
    try:
        pipe = StableDiffusionXLPipeline.from_pretrained(
            "stabilityai/sdxl-turbo",
            torch_dtype=torch.float16,
            variant="fp16",
            use_safetensors=True,
        )
        print("Pipeline loaded.")
    except Exception as e:
        print(f"Error loading pipeline: {e}")
        print(
            "Please ensure you have the necessary libraries installed, sufficient VRAM, and are logged in (`huggingface-cli login`)."
        )
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
        gc.collect()
        return

    if torch.cuda.is_available():
        print("Moving pipeline to GPU...")
        try:
            pipe = pipe.to("cuda")
            print("Pipeline moved to CUDA.")
        except Exception as e:
            print(f"Error moving pipeline to CUDA: {e}. Trying CPU.")
            try:
                pipe = pipe.to("cpu")
                print("Running on CPU.")
            except Exception as cpu_e:
                print(f"Error moving pipeline to CPU: {cpu_e}. Exiting.")
                del pipe
                gc.collect()
                return
    else:
        print("Warning: CUDA not available. Running on CPU will be very slow.")
        try:
            pipe = pipe.to("cpu")
        except Exception as e:
            print(f"Error moving pipeline to CPU: {e}. Exiting.")
            del pipe
            gc.collect()
            return

    for class_name in classes:
        class_folder = os.path.join(base_folder, class_name)
        os.makedirs(class_folder, exist_ok=True)
        print(f"\n--- Generating images for class: '{class_name}' ---")
        print(f"Saving to: {class_folder}")

        current_concepts = concept_map.get(class_name)
        if (
            not current_concepts
            or "descriptor_type" not in current_concepts
            or "context_action" not in current_concepts
        ):
            print(
                f"Warning: Incomplete or missing concepts for class '{class_name}'. Skipping this class."
            )
            continue

        descriptors = current_concepts["descriptor_type"]
        contexts = current_concepts["context_action"]

        if not descriptors or not contexts:
            print(
                f"Warning: Empty descriptor or context list for class '{class_name}'. Skipping this class."
            )
            continue

        print(
            f"Found {len(descriptors)} descriptors and {len(contexts)} contexts for {class_name}."
        )

        generated_count = 0
        pbar = tqdm(total=num_images_per_class, desc=f"Generating {class_name}")
        while generated_count < num_images_per_class:
            image_to_save: Optional[Image.Image] = None
            try:
                selected_descriptor: str = random.choice(descriptors)
                selected_context: str = random.choice(contexts)
                selected_quality: str = random.choice(quality_modifiers)

                prompt: str = f"{selected_quality} photo of a {selected_descriptor} {class_name} {selected_context}"

                with torch.inference_mode():
                    image_result = pipe(
                        prompt=prompt,
                        guidance_scale=0.0,
                        num_inference_steps=1,
                        width=512,
                        height=512,
                    )
                    if image_result and image_result.images:
                        image_to_save = image_result.images[0]
                    else:
                        tqdm.write(
                            f"\nWarning: Image generation failed for prompt: '{prompt}'. No image returned."
                        )
                        continue

                if image_to_save is None:
                    tqdm.write(
                        f"\nError: Image object is None after generation for prompt: '{prompt}'. Skipping."
                    )
                    continue

                output_filename: str = f"{class_name}_{generated_count:06d}.png"
                output_path: str = os.path.join(class_folder, output_filename)

                image_to_save.save(output_path)
                generated_count += 1
                pbar.update(1)

            except torch.cuda.OutOfMemoryError:
                pbar.write(
                    f"\nCUDA OutOfMemoryError for class '{class_name}', prompt: '{prompt}'. Skipping image, clearing cache."
                )
                if image_to_save is not None:
                    del image_to_save
                if "image_result" in locals():
                    del image_result
                if torch.cuda.is_available():
                    torch.cuda.empty_cache()
                gc.collect()
                import time

                time.sleep(1)
                continue

            except Exception as e:
                pbar.write(
                    f"\nError generating image {generated_count} for class '{class_name}' with prompt: '{prompt}'"
                )
                pbar.write(f"Error details: {e}")
                if image_to_save is not None:
                    del image_to_save
                if "image_result" in locals():
                    del image_result
                if torch.cuda.is_available():
                    torch.cuda.empty_cache()
                gc.collect()
                continue
            finally:
                if image_to_save is not None:
                    try:
                        del image_to_save
                    except NameError:
                        pass
                if "image_result" in locals():
                    try:
                        del image_result
                    except NameError:
                        pass

        pbar.close()
        print(f"Finished generating {generated_count} images for class '{class_name}'.")
        print("Clearing cache between classes...")
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
        print("Cache cleared.")

    print(
        f"\nFinished generating images for all specified classes. Saved in {base_folder}"
    )
    print("Final cleanup...")
    if pipe is not None:
        try:
            del pipe
        except NameError:
            pass
    gc.collect()
    if torch.cuda.is_available():
        print("Final CUDA cache clear...")
        torch.cuda.empty_cache()
    print("Cleanup complete.")


if __name__ == "__main__":
    if torch.cuda.is_available():
        print("Initial CUDA cache clear...")
        torch.cuda.empty_cache()
        gc.collect()
        print("Cache cleared.")

    make_cifar10_style_images(
        base_folder="./cifar10_sdxl_turbo_100k_per_class",
        num_images_per_class=100000,
        classes=cifar10_classes,
        concept_map=class_specific_concepts,
    )

    print("\nScript finished.")
